name: PR Comment

on: [pull_request, pull_request_target]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: angelikatyborska/pr-commenter-action@97e4da967b377bf97ce50bfa102a39c8decf4ace
